//! Debug: feed the Python-reference encoder output through the Rust
//! RNN-T decoder + tokenizer. If Japanese text comes out, the Python
//! reference encoder in `scripts/dump-encoder-fixtures.py` is correct
//! and any drift is in the Rust encoder. If the output is gibberish,
//! both implementations are diverging from NeMo and the Python ref
//! itself needs fixing first.
//!
//! Skipped when the prerequisites aren't present:
//!   - `/tmp/reazon.gguf` (converted from .nemo)
//!   - `/tmp/reazon.tokenizer.model` (companion SP model)
//!   - `crates/fastconformer-core/tests/fixtures/reazonspeech-nemo-v2/encoder/encoder_output.npy`
//!     (generated by `scripts/dump-encoder-fixtures.py`)

use std::fs;
use std::path::{Path, PathBuf};

use fastconformer_core::encoder::EncoderOutput;
use fastconformer_core::{log_mel_spectrogram, Config, SentencePieceTokenizer};
use gguf_loader::GgufFile;
use reazonspeech_backend::{decoder::RnntDecoder, encoder};

fn read_npy_f32_2d(path: &Path) -> Option<(Vec<f32>, [usize; 2])> {
    let bytes = fs::read(path).ok()?;
    if &bytes[..6] != b"\x93NUMPY" {
        return None;
    }
    let major = bytes[6];
    let (header_len, header_start) = match major {
        1 => (
            u16::from_le_bytes([bytes[8], bytes[9]]) as usize,
            10_usize,
        ),
        2 | 3 => (
            u32::from_le_bytes([bytes[8], bytes[9], bytes[10], bytes[11]]) as usize,
            12_usize,
        ),
        _ => return None,
    };
    let header = std::str::from_utf8(&bytes[header_start..header_start + header_len]).ok()?;
    if !header.contains("'<f4'") {
        return None;
    }
    let open = header.find('(')?;
    let close = header[open..].find(')')? + open;
    let dims: Vec<usize> = header[open + 1..close]
        .split(',')
        .filter_map(|s| s.trim().parse::<usize>().ok())
        .collect();
    if dims.len() != 2 {
        return None;
    }
    let body = &bytes[header_start + header_len..];
    let n = dims[0] * dims[1];
    let mut out = Vec::with_capacity(n);
    for i in 0..n {
        let b = &body[i * 4..i * 4 + 4];
        out.push(f32::from_le_bytes([b[0], b[1], b[2], b[3]]));
    }
    Some((out, [dims[0], dims[1]]))
}

#[test]
fn python_ref_encoder_output_decodes_to_japanese_text() {
    let gguf_path = PathBuf::from("/tmp/reazon.gguf");
    let tok_path = PathBuf::from("/tmp/reazon.tokenizer.model");
    // Prefer NeMo ground-truth dump (from scripts/nemo-truth-dump.py).
    // Fall back to the hand-rolled reference if not present.
    let truth = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../fastconformer-core/tests/fixtures/reazonspeech-nemo-v2/encoder_truth/encoder_output.npy");
    let hand = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../fastconformer-core/tests/fixtures/reazonspeech-nemo-v2/encoder/encoder_output.npy");
    let enc_out_path = if truth.exists() { truth } else { hand };
    eprintln!("using encoder output: {}", enc_out_path.display());

    if !gguf_path.exists() || !tok_path.exists() || !enc_out_path.exists() {
        eprintln!("SKIPPED: missing prerequisites:");
        eprintln!("  gguf:    {} (exists={})", gguf_path.display(), gguf_path.exists());
        eprintln!("  tokens:  {} (exists={})", tok_path.display(), tok_path.exists());
        eprintln!("  enc_out: {} (exists={})", enc_out_path.display(), enc_out_path.exists());
        return;
    }

    let gguf = GgufFile::open(&gguf_path).expect("open gguf");
    let cfg = Config::from_gguf(&gguf).expect("parse config");
    let decoder = RnntDecoder::from_gguf(&gguf, cfg.clone()).expect("load decoder");
    let tokenizer = SentencePieceTokenizer::load(&tok_path).expect("load tokenizer");

    let (data, shape) = read_npy_f32_2d(&enc_out_path).expect("read encoder_output.npy");
    eprintln!("loaded ref encoder output shape: [{}, {}]", shape[0], shape[1]);
    assert_eq!(shape[1], cfg.d_model as usize, "d_model mismatch");

    let enc_out = EncoderOutput {
        data,
        n_frames: shape[0],
        d_model: shape[1],
    };

    let token_ids = decoder.greedy_decode(&enc_out);
    eprintln!("decoded {} token ids", token_ids.len());
    eprintln!("token ids (first 50): {:?}", &token_ids[..token_ids.len().min(50)]);

    let text = tokenizer.detokenize(&token_ids).expect("detokenize");
    eprintln!("text: {text:?}");

    // We don't assert specific content yet — just want to see what comes out.
    // For Japanese audio the expected text starts with "嫌だ" and continues
    // with conversation.
    assert!(
        !text.is_empty(),
        "no text decoded — Python ref encoder may be broken"
    );
}

#[test]
fn rust_full_pipeline_decodes_japanese_test_wav() {
    let gguf_path = PathBuf::from("/tmp/reazon.gguf");
    let tok_path = PathBuf::from("/tmp/reazon.tokenizer.model");
    let wav_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../third-party/whisper.cpp/samples/japanese_test.wav");
    if !gguf_path.exists() || !tok_path.exists() || !wav_path.exists() {
        eprintln!("SKIPPED: missing prerequisites");
        return;
    }
    let gguf = GgufFile::open(&gguf_path).expect("open gguf");
    let cfg = Config::from_gguf(&gguf).expect("parse config");
    let enc = encoder::load(&gguf, cfg.clone()).expect("load encoder");
    let decoder = RnntDecoder::from_gguf(&gguf, cfg.clone()).expect("load decoder");
    let tokenizer = SentencePieceTokenizer::load(&tok_path).expect("load tokenizer");

    let audio = read_wav_16k_mono(&wav_path).expect("read wav");
    let mel = log_mel_spectrogram(&audio, &cfg);
    eprintln!("mel: frames={} n_mels={}", mel.n_frames, mel.n_mels);

    let enc_out = enc.forward(&mel.data, mel.n_frames).expect("encoder forward");
    eprintln!("encoder out: n_frames={} d_model={}", enc_out.n_frames, enc_out.d_model);

    let token_ids = decoder.greedy_decode(&enc_out);
    eprintln!("decoded {} tokens", token_ids.len());
    eprintln!("first 30: {:?}", &token_ids[..token_ids.len().min(30)]);
    let text = tokenizer.detokenize(&token_ids).expect("detokenize");
    eprintln!("text: {text:?}");
    assert!(!text.is_empty());
}

/// Isolated test: feed NeMo's `block0_pre_conv` (LN'd input to conv) into
/// Rust's conv module and compare against NeMo's `block0_conv_out`.
#[test]
fn rust_conv_only_vs_nemo_truth() {
    let gguf_path = PathBuf::from("/tmp/reazon.gguf");
    let truth_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../fastconformer-core/tests/fixtures/reazonspeech-nemo-v2/encoder_truth");
    if !gguf_path.exists() || !truth_dir.join("block0_pre_conv.npy").exists() {
        eprintln!("SKIPPED");
        return;
    }
    let gguf = GgufFile::open(&gguf_path).expect("open gguf");
    let cfg = Config::from_gguf(&gguf).expect("parse config");
    let enc = encoder::load(&gguf, cfg.clone()).expect("load encoder");

    let (pre_conv, _) = read_npy_f32_2d(&truth_dir.join("block0_pre_conv.npy")).expect("pre_conv");
    let (truth_conv_out, _) =
        read_npy_f32_2d(&truth_dir.join("block0_conv_out.npy")).expect("conv_out");
    let dm = cfg.d_model as usize;
    let t_out = pre_conv.len() / dm;

    let conv = &enc.blocks[0].conv;
    let mut x = pre_conv.clone();
    conv.forward_residual_no_ln(&mut x, t_out);
    let conv_out_rust: Vec<f32> = x.iter().zip(pre_conv.iter()).map(|(a, b)| a - b).collect();

    let nf = truth_conv_out.len() / dm;
    let valid = (nf - 1) * dm;
    let mut max_abs = 0f32;
    let mut sum_abs = 0.0_f64;
    let mut worst = (0usize, 0.0_f32);
    for i in 0..valid {
        let d = (conv_out_rust[i] - truth_conv_out[i]).abs();
        if d > max_abs {
            max_abs = d;
            worst = (i, d);
        }
        sum_abs += d as f64;
    }
    let mean_abs = (sum_abs / valid as f64) as f32;
    println!(
        "Rust conv_out (from NeMo pre_conv): max_abs={:.4e}, mean_abs={:.4e}",
        max_abs, mean_abs
    );
    let t = worst.0 / dm;
    let c = worst.0 % dm;
    println!(
        "  worst (t={t}, c={c}): ours={} truth={}",
        conv_out_rust[worst.0], truth_conv_out[worst.0]
    );
    let truth_max = truth_conv_out.iter().take(valid).map(|x| x.abs()).fold(0f32, f32::max);
    let truth_mean = truth_conv_out.iter().take(valid).map(|x| x.abs() as f64).sum::<f64>() / valid as f64;
    println!("  truth magnitudes: max_abs={truth_max} mean_abs={truth_mean:.4}");

    // Per-frame max diff to localize drift.
    println!("  per-frame max-abs diff:");
    for t in 0..nf {
        let mut fmax = 0f32;
        for c in 0..dm {
            let d = (conv_out_rust[t * dm + c] - truth_conv_out[t * dm + c]).abs();
            if d > fmax {
                fmax = d;
            }
        }
        if fmax > 0.1 {
            println!("    t={t}: {:.4}", fmax);
        }
    }
}

/// Isolated test: feed NeMo's `block0_pre_attn` (the LN'd input to attn)
/// into Rust's attention math and compare against NeMo's `block0_attn_out`.
/// Bypasses upstream LN to localize attention bugs only.
#[test]
fn rust_attention_only_vs_nemo_truth() {
    let gguf_path = PathBuf::from("/tmp/reazon.gguf");
    let truth_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../fastconformer-core/tests/fixtures/reazonspeech-nemo-v2/encoder_truth");
    if !gguf_path.exists() || !truth_dir.join("block0_pre_attn.npy").exists() {
        eprintln!("SKIPPED");
        return;
    }
    let gguf = GgufFile::open(&gguf_path).expect("open gguf");
    let cfg = Config::from_gguf(&gguf).expect("parse config");
    let enc = encoder::load(&gguf, cfg.clone()).expect("load encoder");

    let (pre_attn, _) = read_npy_f32_2d(&truth_dir.join("block0_pre_attn.npy")).expect("pre_attn");
    let (truth_attn_out, _) = read_npy_f32_2d(&truth_dir.join("block0_attn_out.npy"))
        .expect("attn_out");
    let dm = cfg.d_model as usize;
    let t_out = pre_attn.len() / dm;

    // Run Rust's attention math directly. The attention's forward_residual
    // applies LN internally then adds residual. We want to bypass both.
    // Manually invoke the inner math by:
    //   - Treat `pre_attn` as already-LN'd input
    //   - Build Q, K, V from it directly (no LN re-apply)
    //   - Compute attn_out (the projected output, before residual)
    //
    // Easiest path: temporarily make the LN an identity (γ=1, β=0, +eps that
    // normalizes back to zero-mean unit-std would NOT give identity — instead
    // we monkey-patch the LN to skip).
    //
    // We use a different tactic: call forward_residual with x=pre_attn AND
    // ALSO with x=0; the difference is the attn_out (since LN(0)=0 → attn(0)=0
    // + out_bias). Then attn_out_for_pre_attn = forward(pre_attn) - pre_attn.
    // But forward applies LN(pre_attn) internally; if pre_attn is already LN'd,
    // re-LN should yield the same vector since LN is idempotent only when the
    // statistics are unchanged — which they are if the input is already mean-0
    // unit-std. NeMo's pre_attn comes from norm_self_att(after_ff1) which has
    // γ/β applied, so the values are NOT mean-0 unit-std globally.

    // Cleaner path: build a separate MHA module with `ln_gamma=1, ln_beta=0`
    // and `eps` huge — that makes LN a no-op (subtract mean, divide by ~1).
    // But that perturbs the values by mean subtraction.
    //
    // Best: just call forward and subtract residual.
    let attn = &enc.blocks[0].attn;
    let mut x = pre_attn.clone();
    attn.forward_residual_no_ln(
        &mut x,
        t_out,
        fastconformer_core::encoder::AttentionMode::LocalGlobal {
            local_window: cfg.local_window as usize,
            global_tokens: cfg.global_tokens as usize,
        },
    );
    let attn_out_rust: Vec<f32> = x.iter().zip(pre_attn.iter()).map(|(a, b)| a - b).collect();

    let dm_v = 1024usize;
    let nf = truth_attn_out.len() / dm_v;
    let valid = (nf - 1) * dm_v;
    let mut max_abs = 0f32;
    let mut sum_abs = 0.0_f64;
    let mut worst = (0usize, 0.0_f32);
    for i in 0..valid {
        let d = (attn_out_rust[i] - truth_attn_out[i]).abs();
        if d > max_abs {
            max_abs = d;
            worst = (i, d);
        }
        sum_abs += d as f64;
    }
    let mean_abs = (sum_abs / valid as f64) as f32;
    println!(
        "Rust attn_out (from NeMo pre_attn input): max_abs={:.4e}, mean_abs={:.4e}",
        max_abs, mean_abs
    );
    let t = worst.0 / dm_v;
    let c = worst.0 % dm_v;
    println!(
        "  worst (t={t}, c={c}): ours={} truth={}",
        attn_out_rust[worst.0], truth_attn_out[worst.0]
    );
    // Also print magnitudes for context.
    let truth_max = truth_attn_out.iter().take(valid).map(|x| x.abs()).fold(0f32, f32::max);
    let truth_mean = truth_attn_out.iter().take(valid).map(|x| x.abs() as f64).sum::<f64>() / valid as f64;
    println!("  truth magnitudes: max_abs={truth_max} mean_abs={truth_mean:.4}");
}

/// Block 0 internal stage-by-stage comparison vs NeMo block-internals truth.
#[test]
fn rust_block0_internals_vs_nemo_truth() {
    let gguf_path = PathBuf::from("/tmp/reazon.gguf");
    let truth_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../fastconformer-core/tests/fixtures/reazonspeech-nemo-v2/encoder_truth");
    let wav_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../third-party/whisper.cpp/samples/japanese_test.wav");
    if !gguf_path.exists() || !truth_dir.join("block0_after_ff1.npy").exists() || !wav_path.exists() {
        eprintln!("SKIPPED: missing prerequisites");
        return;
    }
    let gguf = GgufFile::open(&gguf_path).expect("open gguf");
    let cfg = Config::from_gguf(&gguf).expect("parse config");
    let enc = encoder::load(&gguf, cfg.clone()).expect("load encoder");

    let audio = read_wav_16k_mono(&wav_path).expect("read wav");
    let mel = log_mel_spectrogram(&audio, &cfg);

    // Subsample + xscale (replicating encoder.forward up to block 0 input).
    let (mut x, t_out) = enc.subsample.forward(&mel.data, mel.n_frames);
    let xscale = (cfg.d_model as f32).sqrt();
    for v in x.iter_mut() {
        *v *= xscale;
    }

    println!("\n=== Rust block 0 internals vs NeMo truth ===");
    println!("{:<30} {:>12} {:>12}", "stage", "max_abs", "mean_abs");

    let mut snapshots: std::collections::HashMap<String, Vec<f32>> =
        std::collections::HashMap::new();
    let valid_frames = t_out.saturating_sub(1);
    let block_input = x.clone();
    enc.blocks[0].forward_dump(&mut x, t_out, valid_frames, |name, x| {
        snapshots.insert(name.to_string(), x.to_vec());
    });
    // Print Rust FF contribution at frame 0.
    if let Some(after_ff1) = snapshots.get("after_ff1") {
        let ff_contrib: Vec<f32> = after_ff1
            .iter()
            .zip(block_input.iter())
            .map(|(a, b)| a - b)
            .collect();
        println!("Rust FF contribution at frame 0 [:5]: {:?}", &ff_contrib[..5]);
    }

    let compare = |label: &str, ours: &[f32], truth: &[f32]| {
        let dm = 1024usize;
        let nf = truth.len() / dm;
        let valid = (nf - 1) * dm;
        let mut max_abs = 0f32;
        let mut sum_abs = 0.0_f64;
        for i in 0..valid {
            let d = (ours[i] - truth[i]).abs();
            if d > max_abs {
                max_abs = d;
            }
            sum_abs += d as f64;
        }
        let mean_abs = (sum_abs / valid as f64) as f32;
        println!("{label:<30} {:>12.4e} {:>12.4e}", max_abs, mean_abs);
    };

    let load = |name: &str| -> Option<Vec<f32>> {
        let path = truth_dir.join(format!("block0_{name}.npy"));
        if !path.exists() {
            return None;
        }
        read_npy_f32_2d(&path).map(|(d, _)| d)
    };
    for stage in &["after_ff1", "after_attn", "after_conv", "after_ff2", "block_out"] {
        if let (Some(truth), Some(ours)) = (load(stage), snapshots.get(*stage)) {
            compare(stage, ours, &truth);
        }
    }

    // Derived: ours_attn_out = ours_after_attn - ours_after_ff1, compare vs truth attn_out.
    if let (Some(t_attn_out), Some(t_pre_attn), Some(o_after_ff1), Some(o_after_attn)) = (
        load("attn_out"),
        load("pre_attn"),
        snapshots.get("after_ff1"),
        snapshots.get("after_attn"),
    ) {
        let ours_attn_out: Vec<f32> = o_after_attn
            .iter()
            .zip(o_after_ff1.iter())
            .map(|(a, f)| a - f)
            .collect();
        compare("attn_out (derived)", &ours_attn_out, &t_attn_out);
        // pre_attn = norm_self_att(after_ff1). Rust applies LN internally.
        // We can recompute Rust's "pre_attn" by applying LN to after_ff1 with the
        // attn's ln gamma/beta.
        let ln_g = &enc.blocks[0].attn.ln_gamma;
        let ln_b = &enc.blocks[0].attn.ln_beta;
        let dm = 1024usize;
        let mut ours_pre_attn = o_after_ff1.clone();
        for t in 0..t_out {
            let row = &mut ours_pre_attn[t * dm..(t + 1) * dm];
            fastconformer_core::encoder::layer_norm(row, ln_g, ln_b, 1e-5);
        }
        compare("pre_attn (derived)", &ours_pre_attn, &t_pre_attn);
    }

    // Same trick for conv: conv_out = after_conv - after_attn.
    if let (Some(t_conv_out), Some(o_after_attn), Some(o_after_conv)) = (
        load("conv_out"),
        snapshots.get("after_attn"),
        snapshots.get("after_conv"),
    ) {
        let ours_conv_out: Vec<f32> = o_after_conv
            .iter()
            .zip(o_after_attn.iter())
            .map(|(c, a)| c - a)
            .collect();
        compare("conv_out (derived)", &ours_conv_out, &t_conv_out);
    }
}

/// Walk Rust encoder layer-by-layer and report max_abs vs NeMo truth at
/// each stage. Prints results; doesn't assert per stage (the goal is to
/// surface the first divergence so we can locate the buggy module).
#[test]
fn rust_encoder_layer_comparison_vs_nemo_truth() {
    let gguf_path = PathBuf::from("/tmp/reazon.gguf");
    let truth_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../fastconformer-core/tests/fixtures/reazonspeech-nemo-v2/encoder_truth");
    let wav_path = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../../third-party/whisper.cpp/samples/japanese_test.wav");
    if !gguf_path.exists() || !truth_dir.join("after_pre_encode.npy").exists() || !wav_path.exists() {
        eprintln!("SKIPPED: missing prerequisites");
        return;
    }
    let gguf = GgufFile::open(&gguf_path).expect("open gguf");
    let cfg = Config::from_gguf(&gguf).expect("parse config");
    let enc = encoder::load(&gguf, cfg.clone()).expect("load encoder");

    let audio = read_wav_16k_mono(&wav_path).expect("read wav");
    let mel = log_mel_spectrogram(&audio, &cfg);

    let mut report: Vec<(String, f32, f32)> = Vec::new();
    let load_truth = |name: &str| -> Option<Vec<f32>> {
        let path = truth_dir.join(format!("{name}.npy"));
        if !path.exists() {
            return None;
        }
        read_npy_f32_2d(&path).map(|(d, _)| d)
    };
    let n_frames = (mel.n_frames - 1).div_ceil(8); // approx encoder time
    let _ = n_frames;
    let _ = enc.forward_dump(&mel.data, mel.n_frames, |name, x| {
        if let Some(truth) = load_truth(name) {
            if truth.len() != x.len() {
                eprintln!("[{name}] size mismatch: ours={} truth={}", x.len(), truth.len());
                return;
            }
            // Skip the last encoder time-frame (padding artifact in NeMo).
            let dm = 1024;
            let nf = truth.len() / dm;
            let valid = (nf - 1) * dm;
            let mut max_abs = 0.0_f32;
            let mut worst = (0usize, 0.0_f32);
            let mut sum_abs = 0.0_f64;
            for i in 0..valid {
                let d = (x[i] - truth[i]).abs();
                if d > max_abs {
                    max_abs = d;
                    worst = (i, d);
                }
                sum_abs += d as f64;
            }
            let mean_abs = (sum_abs / valid as f64) as f32;
            let t = worst.0 / dm;
            let m = worst.0 % dm;
            report.push((name.to_string(), max_abs, mean_abs));
            if name == "after_pre_encode" {
                println!("[{name}] worst (t={t}, m={m}): ours={} truth={}",
                         x[worst.0], truth[worst.0]);
            }
        }
    });
    println!("\n=== Rust encoder vs NeMo truth (per-stage) ===");
    println!("{:<30} {:>12} {:>12}", "stage", "max_abs", "mean_abs");
    for (n, ma, me) in &report {
        println!("{:<30} {:>12.4e} {:>12.4e}", n, ma, me);
    }
}

fn read_wav_16k_mono(path: &Path) -> Result<Vec<f32>, String> {
    let bytes = fs::read(path).map_err(|e| format!("{e}"))?;
    let mut pos = 12_usize;
    let mut data: &[u8] = &[];
    while pos + 8 <= bytes.len() {
        let id = &bytes[pos..pos + 4];
        let sz = u32::from_le_bytes([
            bytes[pos + 4], bytes[pos + 5], bytes[pos + 6], bytes[pos + 7]
        ]) as usize;
        if id == b"data" {
            data = &bytes[pos + 8..pos + 8 + sz];
        }
        pos += 8 + sz + (sz & 1);
    }
    let mut out = Vec::with_capacity(data.len() / 2);
    for i in (0..data.len()).step_by(2) {
        let s = i16::from_le_bytes([data[i], data[i + 1]]);
        out.push(s as f32 / 32768.0);
    }
    Ok(out)
}
