//! Layer-by-layer reference tests.
//!
//! Compares whisper.cpp output against Python OpenAI whisper reference fixtures.
//! Reference data is generated by `scripts/generate_test_fixtures.py`.
//!
//! Test coverage:
//! - Model architecture parameters (n_vocab, n_layers, n_heads, etc.)
//! - Full transcription text (segment-level)
//! - Segment timestamps
//! - Language detection
//! - Token-level output
//!
//! Requires:
//! - Model: third-party/whisper.cpp/models/ggml-tiny.en.bin
//! - Fixture: tests/fixtures/reference_tiny_en_jfk.json

use std::ffi::{CStr, CString};
use std::path::{Path, PathBuf};

use any_stt::config::Backend;
use any_stt::SttEngine;
use whisper_backend::ffi::*;
use whisper_backend::WhisperEngine;

// ---- Helpers ----

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .unwrap()
}

fn model_path() -> PathBuf {
    repo_root().join("third-party/whisper.cpp/models/ggml-tiny.en.bin")
}

fn jfk_wav_path() -> PathBuf {
    repo_root().join("third-party/whisper.cpp/samples/jfk.wav")
}

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/reference_tiny_en_jfk.json")
}

fn read_wav(path: &Path) -> Vec<f32> {
    let reader = hound::WavReader::open(path).expect("failed to open WAV");
    let spec = reader.spec();
    assert_eq!(spec.channels, 1);
    assert_eq!(spec.sample_rate, 16000);
    let max_val = (1 << (spec.bits_per_sample - 1)) as f32;
    reader
        .into_samples::<i32>()
        .map(|s| s.unwrap() as f32 / max_val)
        .collect()
}

#[derive(serde::Deserialize)]
struct Fixture {
    model: String,
    mel_spectrogram: MelData,
    encoder: EncoderData,
    decoder: DecoderData,
    transcription: TranscriptionData,
}

#[derive(serde::Deserialize)]
struct MelData {
    audio_samples: usize,
    audio_duration_s: f64,
    mel_padded: TensorStats,
}

#[derive(serde::Deserialize)]
struct TensorStats {
    shape: Vec<usize>,
    min: f64,
    max: f64,
    mean: f64,
    std: f64,
    head: Vec<f64>,
}

#[derive(serde::Deserialize)]
struct EncoderData {
    final_output: TensorStats,
    blocks: std::collections::HashMap<String, serde_json::Value>,
}

#[derive(serde::Deserialize)]
struct DecoderData {
    logits: TensorStats,
    blocks: std::collections::HashMap<String, serde_json::Value>,
}

#[derive(serde::Deserialize)]
struct TranscriptionData {
    text: String,
    language: String,
    segments: Vec<SegmentData>,
}

#[derive(serde::Deserialize)]
struct SegmentData {
    id: usize,
    start: f64,
    end: f64,
    text: String,
    tokens: Vec<i64>,
}

fn load_fixture() -> Fixture {
    let path = fixture_path();
    if !path.exists() {
        panic!(
            "Fixture not found: {}. Run: python scripts/generate_test_fixtures.py",
            path.display()
        );
    }
    let data = std::fs::read_to_string(&path).unwrap();
    serde_json::from_str(&data).unwrap()
}

fn skip_if_no_model() -> bool {
    let p = model_path();
    if !p.exists() {
        eprintln!("SKIPPED: model not found at {}", p.display());
        return true;
    }
    false
}

/// Create a raw whisper context for low-level FFI tests.
unsafe fn create_ctx() -> *mut WhisperContext {
    let path = CString::new(model_path().to_str().unwrap()).unwrap();
    let mut cparams = whisper_context_default_params();
    cparams.use_gpu = false;
    whisper_init_from_file_with_params(path.as_ptr(), cparams)
}

// ======================================================================
// Model architecture tests
// ======================================================================

#[test]
fn model_architecture_matches_tiny_en() {
    if skip_if_no_model() {
        return;
    }
    let ctx = unsafe { create_ctx() };
    assert!(!ctx.is_null());

    unsafe {
        // tiny.en: 4 encoder layers, 4 decoder layers, 6 heads, 384 state
        assert_eq!(whisper_model_n_vocab(ctx), 51864);
        assert_eq!(whisper_model_n_audio_ctx(ctx), 1500);
        assert_eq!(whisper_model_n_audio_state(ctx), 384);
        assert_eq!(whisper_model_n_audio_head(ctx), 6);
        assert_eq!(whisper_model_n_audio_layer(ctx), 4);
        assert_eq!(whisper_model_n_text_ctx(ctx), 448);
        assert_eq!(whisper_model_n_text_state(ctx), 384);
        assert_eq!(whisper_model_n_text_head(ctx), 6);
        assert_eq!(whisper_model_n_text_layer(ctx), 4);
        assert_eq!(whisper_model_n_mels(ctx), 80);

        whisper_free(ctx);
    }
}

// ======================================================================
// Mel spectrogram tests
// ======================================================================

#[test]
fn audio_sample_count_matches_reference() {
    if skip_if_no_model() {
        return;
    }
    let fixture = load_fixture();
    let audio = read_wav(&jfk_wav_path());

    assert_eq!(audio.len(), fixture.mel_spectrogram.audio_samples);
}

#[test]
fn mel_input_shape_matches_reference() {
    let fixture = load_fixture();

    // Mel padded shape should be [80, 3000] for 30s context
    assert_eq!(fixture.mel_spectrogram.mel_padded.shape, vec![80, 3000]);
}

// ======================================================================
// Encoder reference tests
// ======================================================================

#[test]
fn encoder_output_shape_matches_reference() {
    let fixture = load_fixture();

    // Encoder output: [1, 1500, 384] for tiny.en
    assert_eq!(fixture.encoder.final_output.shape, vec![1, 1500, 384]);
}

#[test]
fn encoder_has_4_blocks() {
    let fixture = load_fixture();
    assert_eq!(fixture.encoder.blocks.len(), 4);
    assert!(fixture.encoder.blocks.contains_key("block_0"));
    assert!(fixture.encoder.blocks.contains_key("block_3"));
}

#[test]
fn encoder_block_outputs_are_finite() {
    let fixture = load_fixture();

    for (name, block) in &fixture.encoder.blocks {
        let block: std::collections::HashMap<String, TensorStats> =
            serde_json::from_value(block.clone()).unwrap();

        for (layer_name, stats) in &block {
            assert!(
                stats.mean.is_finite(),
                "encoder {name}/{layer_name}: mean is not finite"
            );
            assert!(
                stats.std.is_finite(),
                "encoder {name}/{layer_name}: std is not finite"
            );
            assert!(
                stats.min <= stats.max,
                "encoder {name}/{layer_name}: min > max"
            );
        }
    }
}

// ======================================================================
// Decoder reference tests
// ======================================================================

#[test]
fn decoder_has_4_blocks() {
    let fixture = load_fixture();
    assert_eq!(fixture.decoder.blocks.len(), 4);
}

#[test]
fn decoder_logits_shape_is_correct() {
    let fixture = load_fixture();

    // Logits: [1, 3, 51864] — 3 tokens (SOT sequence), 51864 vocab
    assert_eq!(fixture.decoder.logits.shape[0], 1);
    assert_eq!(fixture.decoder.logits.shape[2], 51864);
}

#[test]
fn decoder_block_outputs_are_finite() {
    let fixture = load_fixture();

    for (name, block) in &fixture.decoder.blocks {
        let block: std::collections::HashMap<String, TensorStats> =
            serde_json::from_value(block.clone()).unwrap();

        for (layer_name, stats) in &block {
            assert!(
                stats.mean.is_finite(),
                "decoder {name}/{layer_name}: mean is not finite"
            );
            assert!(
                stats.std.is_finite(),
                "decoder {name}/{layer_name}: std is not finite"
            );
        }
    }
}

#[test]
fn decoder_blocks_have_cross_attention() {
    let fixture = load_fixture();

    for (name, block) in &fixture.decoder.blocks {
        let block: std::collections::HashMap<String, TensorStats> =
            serde_json::from_value(block.clone()).unwrap();

        assert!(
            block.contains_key("cross_attn_output"),
            "decoder {name}: missing cross_attn_output"
        );
        assert!(
            block.contains_key("cross_attn_ln_output"),
            "decoder {name}: missing cross_attn_ln_output"
        );
        assert!(
            block.contains_key("self_attn_output"),
            "decoder {name}: missing self_attn_output"
        );
        assert!(
            block.contains_key("mlp_output"),
            "decoder {name}: missing mlp_output"
        );
    }
}

// ======================================================================
// Full transcription comparison (whisper.cpp vs Python reference)
// ======================================================================

#[test]
fn transcription_text_matches_reference() {
    if skip_if_no_model() {
        return;
    }
    let fixture = load_fixture();
    let hw = any_stt::detect_hardware();
    let engine = WhisperEngine::new(&model_path(), "en", Backend::Cpu, hw).unwrap();
    let audio = read_wav(&jfk_wav_path());

    let result = engine.transcribe(&audio).unwrap();
    let cpp_text = result.text.trim().to_lowercase();
    let py_text = fixture.transcription.text.trim().to_lowercase();

    eprintln!("whisper.cpp: {cpp_text:?}");
    eprintln!("Python ref:  {py_text:?}");

    // Core content must match. Allow minor punctuation/whitespace differences.
    assert!(
        cpp_text.contains("ask not what your country can do for you"),
        "missing core phrase 1 in whisper.cpp output: {cpp_text:?}"
    );
    assert!(
        cpp_text.contains("ask what you can do for your country"),
        "missing core phrase 2 in whisper.cpp output: {cpp_text:?}"
    );

    // Words should largely overlap
    let py_words: Vec<&str> = py_text.split_whitespace().collect();
    let cpp_words: Vec<&str> = cpp_text.split_whitespace().collect();
    let matching = py_words
        .iter()
        .filter(|w| cpp_words.contains(w))
        .count();
    let overlap = matching as f64 / py_words.len() as f64;
    assert!(
        overlap >= 0.85,
        "word overlap too low: {overlap:.2} ({matching}/{}) — cpp={cpp_text:?} py={py_text:?}",
        py_words.len()
    );
}

#[test]
fn transcription_language_matches_reference() {
    if skip_if_no_model() {
        return;
    }
    let fixture = load_fixture();
    let hw = any_stt::detect_hardware();
    let engine = WhisperEngine::new(&model_path(), "en", Backend::Cpu, hw).unwrap();
    let audio = read_wav(&jfk_wav_path());

    let result = engine.transcribe(&audio).unwrap();
    assert_eq!(result.language, fixture.transcription.language);
}

#[test]
fn segment_count_matches_reference() {
    if skip_if_no_model() {
        return;
    }
    let fixture = load_fixture();

    let ctx = unsafe { create_ctx() };
    assert!(!ctx.is_null());

    let audio = read_wav(&jfk_wav_path());
    let params = unsafe { shim_default_params(WhisperSamplingStrategy::Greedy) };
    let lang = CString::new("en").unwrap();
    unsafe {
        shim_params_set_language(params, lang.as_ptr());
        shim_params_set_print_progress(params, false);
        shim_params_set_print_realtime(params, false);
        shim_params_set_print_timestamps(params, false);
    }

    let ret = unsafe { shim_whisper_full(ctx, params, audio.as_ptr(), audio.len() as i32) };
    unsafe { shim_free_params(params) };
    assert_eq!(ret, 0);

    let n_segments = unsafe { whisper_full_n_segments(ctx) } as usize;
    eprintln!("whisper.cpp segments: {n_segments}");
    eprintln!("Python ref segments:  {}", fixture.transcription.segments.len());

    // Segment count may differ slightly between implementations.
    // Allow a tolerance of ±1.
    let diff = (n_segments as i64 - fixture.transcription.segments.len() as i64).unsigned_abs();
    assert!(
        diff <= 1,
        "segment count differs by {diff}: cpp={n_segments}, py={}",
        fixture.transcription.segments.len()
    );

    unsafe { whisper_free(ctx) };
}

#[test]
fn segment_timestamps_are_reasonable() {
    if skip_if_no_model() {
        return;
    }
    let fixture = load_fixture();

    let ctx = unsafe { create_ctx() };
    let audio = read_wav(&jfk_wav_path());
    let params = unsafe { shim_default_params(WhisperSamplingStrategy::Greedy) };
    let lang = CString::new("en").unwrap();
    unsafe {
        shim_params_set_language(params, lang.as_ptr());
        shim_params_set_print_progress(params, false);
        shim_params_set_print_realtime(params, false);
        shim_params_set_print_timestamps(params, false);
    }
    let ret = unsafe { shim_whisper_full(ctx, params, audio.as_ptr(), audio.len() as i32) };
    unsafe { shim_free_params(params) };
    assert_eq!(ret, 0);

    let n_segments = unsafe { whisper_full_n_segments(ctx) };

    for i in 0..n_segments {
        // whisper.cpp timestamps are in centiseconds (10ms units)
        let t0 = unsafe { whisper_full_get_segment_t0(ctx, i) };
        let t1 = unsafe { whisper_full_get_segment_t1(ctx, i) };
        let t0_s = t0 as f64 / 100.0;
        let t1_s = t1 as f64 / 100.0;

        eprintln!("Segment {i}: {t0_s:.2}s - {t1_s:.2}s");

        // Basic sanity: t0 < t1, both non-negative, within audio duration
        assert!(t0 >= 0, "segment {i}: t0 is negative");
        assert!(t1 > t0, "segment {i}: t1 <= t0");
        assert!(
            t1_s <= fixture.mel_spectrogram.audio_duration_s + 1.0,
            "segment {i}: t1 ({t1_s}s) exceeds audio duration ({}s)",
            fixture.mel_spectrogram.audio_duration_s
        );
    }

    // First segment should start near 0
    if n_segments > 0 {
        let first_t0 = unsafe { whisper_full_get_segment_t0(ctx, 0) } as f64 / 100.0;
        assert!(first_t0 < 2.0, "first segment starts too late: {first_t0}s");
    }

    unsafe { whisper_free(ctx) };
}

#[test]
fn per_segment_text_matches_reference() {
    if skip_if_no_model() {
        return;
    }
    let fixture = load_fixture();

    let ctx = unsafe { create_ctx() };
    let audio = read_wav(&jfk_wav_path());
    let params = unsafe { shim_default_params(WhisperSamplingStrategy::Greedy) };
    let lang = CString::new("en").unwrap();
    unsafe {
        shim_params_set_language(params, lang.as_ptr());
        shim_params_set_print_progress(params, false);
        shim_params_set_print_realtime(params, false);
        shim_params_set_print_timestamps(params, false);
    }
    let ret = unsafe { shim_whisper_full(ctx, params, audio.as_ptr(), audio.len() as i32) };
    unsafe { shim_free_params(params) };
    assert_eq!(ret, 0);

    let n_segments = unsafe { whisper_full_n_segments(ctx) } as usize;

    // Collect all text from whisper.cpp
    let mut cpp_texts = Vec::new();
    for i in 0..n_segments {
        let text_ptr = unsafe { whisper_full_get_segment_text(ctx, i as i32) };
        if !text_ptr.is_null() {
            let text = unsafe { CStr::from_ptr(text_ptr) }
                .to_string_lossy()
                .to_string();
            eprintln!("cpp segment {i}: {text:?}");
            cpp_texts.push(text);
        }
    }

    // Compare individual segments against reference
    let min_segments = n_segments.min(fixture.transcription.segments.len());
    for i in 0..min_segments {
        let cpp = cpp_texts[i].trim().to_lowercase();
        let py = fixture.transcription.segments[i].text.trim().to_lowercase();

        eprintln!("Segment {i} cpp: {cpp:?}");
        eprintln!("Segment {i}  py: {py:?}");

        // Each segment's core words should overlap significantly
        let py_words: Vec<&str> = py.split_whitespace().collect();
        let cpp_words: Vec<&str> = cpp.split_whitespace().collect();
        if py_words.is_empty() {
            continue;
        }
        let matching = py_words.iter().filter(|w| cpp_words.contains(w)).count();
        let overlap = matching as f64 / py_words.len() as f64;
        assert!(
            overlap >= 0.70,
            "segment {i}: word overlap too low: {overlap:.2} — cpp={cpp:?} py={py:?}"
        );
    }

    unsafe { whisper_free(ctx) };
}

#[test]
fn token_probabilities_are_valid() {
    if skip_if_no_model() {
        return;
    }

    let ctx = unsafe { create_ctx() };
    let audio = read_wav(&jfk_wav_path());
    let params = unsafe { shim_default_params(WhisperSamplingStrategy::Greedy) };
    let lang = CString::new("en").unwrap();
    unsafe {
        shim_params_set_language(params, lang.as_ptr());
        shim_params_set_print_progress(params, false);
        shim_params_set_print_realtime(params, false);
        shim_params_set_print_timestamps(params, false);
    }
    let ret = unsafe { shim_whisper_full(ctx, params, audio.as_ptr(), audio.len() as i32) };
    unsafe { shim_free_params(params) };
    assert_eq!(ret, 0);

    let n_segments = unsafe { whisper_full_n_segments(ctx) };

    for i in 0..n_segments {
        let n_tokens = unsafe { whisper_full_n_tokens(ctx, i) };
        assert!(n_tokens > 0, "segment {i}: no tokens");

        for j in 0..n_tokens {
            let token_id = unsafe { whisper_full_get_token_id(ctx, i, j) };
            let token_p = unsafe { whisper_full_get_token_p(ctx, i, j) };

            // Token ID should be within vocab range
            assert!(
                token_id >= 0 && token_id < 51864,
                "segment {i} token {j}: id {token_id} out of range"
            );

            // Probability should be in [0, 1]
            assert!(
                token_p >= 0.0 && token_p <= 1.0,
                "segment {i} token {j}: probability {token_p} out of range"
            );
        }
    }

    unsafe { whisper_free(ctx) };
}

// ======================================================================
// Reference value range validation
// ======================================================================

#[test]
fn encoder_layer_value_ranges_are_reasonable() {
    let fixture = load_fixture();

    // Encoder final output stats from Python
    let enc = &fixture.encoder.final_output;
    assert!(enc.min > -20.0, "encoder output min too low: {}", enc.min);
    assert!(enc.max < 20.0, "encoder output max too high: {}", enc.max);
    assert!(
        enc.mean.abs() < 1.0,
        "encoder output mean too far from 0: {}",
        enc.mean
    );
    assert!(
        enc.std > 0.1 && enc.std < 5.0,
        "encoder output std out of range: {}",
        enc.std
    );
}

#[test]
fn decoder_logits_value_ranges_are_reasonable() {
    let fixture = load_fixture();

    let logits = &fixture.decoder.logits;
    assert!(
        logits.min > -50.0,
        "decoder logits min too low: {}",
        logits.min
    );
    assert!(
        logits.max < 50.0,
        "decoder logits max too high: {}",
        logits.max
    );
}

#[test]
fn encoder_layer_stats_monotonic_check() {
    let fixture = load_fixture();

    // Check that encoder blocks produce progressively transformed representations
    // (std should generally change across layers as features are refined)
    let mut stds = Vec::new();
    for i in 0..4 {
        let block: std::collections::HashMap<String, TensorStats> = serde_json::from_value(
            fixture.encoder.blocks[&format!("block_{i}")].clone(),
        )
        .unwrap();
        stds.push(block["block_output"].std);
    }

    eprintln!("Encoder block output stds: {stds:?}");

    // All stds should be positive and finite
    for (i, s) in stds.iter().enumerate() {
        assert!(s.is_finite() && *s > 0.0, "block {i}: std is {s}");
    }
}

#[test]
fn decoder_cross_attention_activates() {
    let fixture = load_fixture();

    // Cross-attention output should have non-trivial activation
    // (proves encoder output is being used by decoder)
    for i in 0..4 {
        let block: std::collections::HashMap<String, TensorStats> = serde_json::from_value(
            fixture.decoder.blocks[&format!("block_{i}")].clone(),
        )
        .unwrap();

        let cross_attn = &block["cross_attn_output"];
        assert!(
            cross_attn.std > 0.01,
            "decoder block {i}: cross_attn std too low ({}), attention may not be activating",
            cross_attn.std
        );
    }
}
